=== ani-68shende/WTL-assignments/Assign2 XML/movie.dtd
<!ELEMENT movie (md)>
<!ELEMENT md (title,year,imdb,rtomatoes, director, genre)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT imdb (#PCDATA)>
<!ELEMENT rtomatoes (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT genre (#PCDATA)>

=== ani-68shende/WTL-assignments/Assign2 XML/movie.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE movie SYSTEM "movie.dtd">
<?xml-stylesheet type="text/xsl" href="movie.xsl"?>
<movie xsi:noNamespaceSchemaLocation="movie.xsd">
    <md>
        <title>Interstellar</title>
        <year>2014</year>
        <imdb>8.6</imdb>
        <rtomatoes>72%</rtomatoes>
        <director>Christopher Nolan</director>
        <genre>Science Fiction</genre>
    </md>
    <md>
        <title>Martian</title>
        <year>2015</year>
        <imdb>8.0</imdb>
        <rtomatoes>91%</rtomatoes>
        <director>Ridley Scott</director>
        <genre>Thriller</genre>
    </md>
    <md>
        <title>Gravity</title>
        <year>2013</year>
        <imdb>7.7</imdb>
        <rtomatoes>96%</rtomatoes>
        <director>Alfonso Cuar√≥n</director>
        <genre>Science Fiction</genre>
    </md>
    <md>
        <title>Memento</title>
        <year>2000</year>
        <imdb>8.4</imdb>
        <rtomatoes>93%</rtomatoes>
        <director>Christopher Nolan</director>
        <genre>Mystery</genre>
    </md>
    <md>
        <title>Prestige</title>
        <year>2006</year>
        <imdb>8.5</imdb>
        <rtomatoes>76%</rtomatoes>
        <director>Christopher Nolan</director>
        <genre>Drama</genre>
    </md>
    <md>
        <title>Inception</title>
        <year>2010</year>
        <imdb>8.8</imdb>
        <rtomatoes>87%</rtomatoes>
        <director>Christopher Nolan</director>
        <genre>Science Fiction</genre>
    </md>
    <md>
        <title>gehdjd Holmes</title>
        <year>2009</year>
        <imdb>7.6</imdb>
        <rtomatoes>69%</rtomatoes>
        <director>Sir Arthur Conan Doyle</director>
        <genre>Mystery</genre>
    </md>
</movie>
